<a href="https://colab.research.google.com/github/sydoky/Tensorflow-Deep-Learning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


# Creating The Tensors with tf.constant()

In [2]:
#Create a scalar (rank 0 tensor)
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
#Create A Vector (more than 0 dimensions)
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#Create a matrix (more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#conversition into float
another_matrix=tf.constant([[10.,7.],
                            [7.,10.],
                            [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
tensor.ndim

3

# A tensor can have arbitary (unlimited amount of dimensions)
# For example, turning a series of images into tensors with shape(224,224,3,32)
# .224,224 (The first 2 dimensions) are the height and width of the images in pixels
# .3 is the nomber of color channels of the image(red, green, blue)
# .32 is the batch size(The number of images a neural network sees at any one time)



# Tensors - An n-dimensional array of numbers (where n can be any number, a 0 dimension tensor is a scalar, a 1 dimension tensor is a vector)

# (scalar - 10km, vecore - 10km to west)

# **Creating Tensors with tf.variable()**

# tf.Constant --> Immutable (doesn't change) 

# tf.variable --> Mutable

In [11]:
#Create the same tensor with tf.Variable() and tf.constant
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

# For updating below

In [12]:
changeable_tensor[0]=7
changeable_tensor

#you cannot do this way but you can do it the other way see below 

TypeError: ignored

In [13]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# **Creating Random Tensors**

In [14]:
#Create two random tensors 
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

random_1,random_2,random_1==random_2



(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
#seeds (42) have to be the same otherwise I will get false results 
#Create two random tensors 
random_1=tf.random.Generator.from_seed(11)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

random_1,random_2,random_1==random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# **Other ways to make tensors**

In [16]:
#Make a tensor of all ones
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [17]:
#Make a tensor of all zeros
tf.zeros(shape=(3,2))


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [18]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)

A=tf.constant(numpy_A, shape=[2,4,3])
numpy_A,A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

Getting Information from Tensors(shape, rank, size)

Shape:The length(number of elements) of each of the dimensions of a tensor

Rank: The number of tensor dimensions(Scalar rank-0, Vector rank-1, Matrix rank-2, Tensor rank-n)

Axis or Dimension: A particular dimension of a tensor

Size: The total number of item in Tensor

In [19]:
#Create a rank 4 Tensors

rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [20]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [21]:
#Get various attributes of Tensor
print("Datatype of every elements {}".format(rank_4_tensor.dtype))
print("No. of dimensions (rank) {}".format(rank_4_tensor.ndim))
print("Shape of Tensor {}".format(rank_4_tensor.shape))
print("Elements along axis 0 of Tensor {}".format(rank_4_tensor.shape[0]))
print("Elements along last axis of tensor {}".format(rank_4_tensor.shape[-1]))
print("Total nomber of elements  {}".format((tf.size(rank_4_tensor).numpy())))

Datatype of every elements <dtype: 'float32'>
No. of dimensions (rank) 4
Shape of Tensor (2, 3, 4, 5)
Elements along axis 0 of Tensor 2
Elements along last axis of tensor 5
Total nomber of elements  120


In [22]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
#Get The first 2 items of each dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [24]:
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])

In [25]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [26]:
#Get The last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [27]:
#Add an extra Dimensions
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

#compare to cell 28. We added extra dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [28]:
#Expand
tf.expand_dims(rank_2_tensor,axis=-1) #-1 means last axis

#Cell 29 is the same thing it's just a different way of doing 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# **Manipulating Tensors (tensor operations)**

# **Basic Operations**

In [33]:
#add values to a tensor using the addition operator 
tensor=tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [34]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [35]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# **Matrix Manipulation**

In [37]:
print(tensor)

#this is the original tensor

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [38]:
tf.matmul(tensor, tensor)

#here we multiply tensor by tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
tensor @ tensor

#the exact same thing as cell 38 but different way of writing

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
#(3,2)
X=tf.constant([[1,2],
               [3,4],
               [5,6]])

Y=tf.constant([[7,8],
               [9,10],
               [11,12]])

In [41]:
X @ Y

#this way won't work

InvalidArgumentError: ignored

In [42]:
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [43]:
#Transpose 
#[1 2 3
# 4 5 6]

#[1 4
# 2 5
# 3 3]

#Transpose will convert them into [2, 3] or [3, 2] 2rows * 3rows


In [44]:
#Transpose
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [45]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [46]:
tf.matmul(a=X,b=Y,transpose_a=True,transpose_b=False)
# the exact same thing as cell 52 but different way of writing
#matmul stands for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

# **Changing The DataType of a tensor**

In [47]:
B=tf.constant([1,7,7.4])

In [48]:
B.dtype

tf.float32

In [49]:
B=tf.cast(B,dtype=tf.float16)
B
#tf stands for tensorflow

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1. , 7. , 7.4], dtype=float16)>

In [50]:
B.dtype

tf.float16

In [51]:
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [52]:
tf.abs(D)
#abs is an absolute value . Sometimes we don't want a negative values like is the cell above. 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [53]:
E=tf.constant(np.random.randint(low=0,high=100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([14, 68, 44, 46, 32, 89, 85, 32, 83, 42, 13, 84, 31, 96, 76, 38, 42,
       88, 43, 98, 18, 71, 21, 24, 63, 52, 77, 56, 99, 96, 33, 12, 16, 93,
       56, 12, 12, 58, 93, 97, 26,  1, 22, 35, 48,  2, 83,  0, 31, 64])>

In [54]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [55]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [56]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [57]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2515>

# **Finding the Positional Maximum and Minimum**

# **Finding the Position of a Tensor Where the Max Values Occur**

In [58]:
F=tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.01964616, 0.08893836, 0.51482555, 0.91911992, 0.21120911,
       0.14676508, 0.9580533 , 0.98187493, 0.61377055, 0.18749394,
       0.42408156, 0.86632012, 0.28622712, 0.41617408, 0.57147705,
       0.39517086, 0.2083627 , 0.67026322, 0.45778673, 0.92686012,
       0.12827812, 0.83652939, 0.05502684, 0.4579174 , 0.63086672,
       0.98233639, 0.9821636 , 0.79849493, 0.03285411, 0.94520002,
       0.4018772 , 0.85581355, 0.63483743, 0.32536126, 0.15453774,
       0.11169775, 0.33755565, 0.84156044, 0.64945377, 0.11404627,
       0.23612253, 0.71899646, 0.80071739, 0.34525491, 0.21853017,
       0.96533483, 0.89647195, 0.87520669, 0.80278409, 0.41082813])>

In [59]:
tf.argmax(F)
#what is the max values, for example 50, but what is the position of that max value? this cells tells the index position. 

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [60]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

# **Squeezing a tensor(Removing all single Dimensions)**

In [61]:
G=tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[78, 52, 38, 74, 94, 30, 96, 17,  9, 17,  6, 90, 22,  3, 94,
           40, 63, 14,  3, 84, 72, 50, 68, 95, 58, 16, 28, 34, 21, 10,
           22,  4, 22,  1,  7, 55,  3, 81, 58, 47, 78, 89, 24, 55, 58,
            0, 31, 40, 96, 93]]]]])>

In [62]:
G=tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
G.shape,G.ndim
#5 in output reprents the dimension. 

(TensorShape([1, 1, 1, 1, 50]), 5)

In [63]:
G_sqz=tf.squeeze(G)
G_sqz.shape, G_sqz.ndim
#the above line shows all stuff

(TensorShape([50]), 1)

# **One_Hot Encoding()**

In [64]:
some_list=[0,1,2,3]

#One hot encode them

tf.one_hot(some_list,depth=5)

#one hot encoding will convert them into 0s and 1s

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [65]:
#Specify custom value for an off encoding

tf.one_hot(some_list,depth=4,on_value="We're Alive", off_value="Offline")
#Instead of 1 is We're Alive and instead of 0 is "Offline"

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're Alive", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're Alive", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're Alive", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're Alive"]], dtype=object)>

# **Squaring,log,square Root**

In [66]:
H=tf.constant(np.arange(1,10))
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [67]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [68]:
tf.sqrt(H)

#we cannot apply square root with dtype=int64

InvalidArgumentError: ignored

In [69]:
#Change H into float32
H=tf.cast(H,dtype=tf.float32)

In [70]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [71]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# **Manipulating tf.variable tensors**

# **.Assign() -Assign a different value to a particular index of a variable tensor**

# **.add_assign()-Add to an existing value and reassign it at a praticular index of a variable tensor bold text ****

Example number 1 below = .Assign() 

In [72]:
#Create a Variable Tensor
I=tf.Variable(np.arange(0,5))
I


<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [73]:
#assign the final value a new value of 50
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [74]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

Example number 2 below = .add_assign()

In [75]:
I.assign_add([10,10,10,10,10])

#I assign 10 to each of them above ---> numpy=array([ 0,  1,  2,  3, 50])>

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [76]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

# **Tensors and Numpy**

# **.np.array()-pass a tensor to convert to an ndarray**

# **.tensor.numpy()-call on a tensor to convert to an ndarray**

# **We are converting Tensors into Numpy and there are 2 ways of doing that**

In [80]:
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [81]:
np.array(J),type(np.array(J))

# It was tensors, now it's array

(array([ 3.,  7., 10.]), numpy.ndarray)

In [84]:
J.numpy()

array([ 3.,  7., 10.])

# **@tf.function**

In [86]:
#Create a simple function 
def function(X,y):
  return x**2+y
x=tf.constant(np.arange(0,10))
y=tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [88]:
#Create the same function and decorate it with tf.function
@tf.function
def tf_function(x,y):
  return x**2+y 

function(x,y)
#this function runs faster than the previous one

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

# **Finding Access to GPUs (graphics processing unit)**

In [89]:
print(tf.config.list_physical_devices("GPU"))

[]


In [2]:
import tensorflow as tf
print(tf.config.list_physical_devices("GPU"))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
!nvidia-smi

Thu Dec 23 17:20:10 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P8    33W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------